// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sr.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "sr.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace sr {
class S2R_RegisterServerDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<S2R_RegisterServer> {
} _S2R_RegisterServer_default_instance_;
class R2S_RegisterServerDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<R2S_RegisterServer> {
} _R2S_RegisterServer_default_instance_;
class S2R_LoginDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<S2R_Login> {
} _S2R_Login_default_instance_;
class R2S_LoginDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<R2S_Login> {
} _R2S_Login_default_instance_;
class S2R_PingDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<S2R_Ping> {
} _S2R_Ping_default_instance_;
class S2R_CreateDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<S2R_Create> {
} _S2R_Create_default_instance_;
class R2S_CreateDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<R2S_Create> {
} _R2S_Create_default_instance_;
class S2R_SaveUserDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<S2R_SaveUser> {
} _S2R_SaveUser_default_instance_;

namespace protobuf_sr_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[8];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2R_RegisterServer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2R_RegisterServer, sid_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2S_RegisterServer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2S_RegisterServer, ret_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2S_RegisterServer, sid_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2R_Login, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2R_Login, tokenid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2R_Login, uid_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2S_Login, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2S_Login, ret_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2S_Login, tokenid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2S_Login, user_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2R_Ping, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2R_Ping, now_time_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2R_Create, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2R_Create, tokenid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2R_Create, user_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2S_Create, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2S_Create, ret_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(R2S_Create, tokenid_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2R_SaveUser, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2R_SaveUser, user_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(S2R_RegisterServer)},
  { 6, -1, sizeof(R2S_RegisterServer)},
  { 13, -1, sizeof(S2R_Login)},
  { 20, -1, sizeof(R2S_Login)},
  { 28, -1, sizeof(S2R_Ping)},
  { 34, -1, sizeof(S2R_Create)},
  { 41, -1, sizeof(R2S_Create)},
  { 48, -1, sizeof(S2R_SaveUser)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_S2R_RegisterServer_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_R2S_RegisterServer_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_S2R_Login_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_R2S_Login_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_S2R_Ping_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_S2R_Create_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_R2S_Create_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_S2R_SaveUser_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "sr.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 8);
}

}  // namespace

void TableStruct::Shutdown() {
  _S2R_RegisterServer_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _R2S_RegisterServer_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _S2R_Login_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
  _R2S_Login_default_instance_.Shutdown();
  delete file_level_metadata[3].reflection;
  _S2R_Ping_default_instance_.Shutdown();
  delete file_level_metadata[4].reflection;
  _S2R_Create_default_instance_.Shutdown();
  delete file_level_metadata[5].reflection;
  _R2S_Create_default_instance_.Shutdown();
  delete file_level_metadata[6].reflection;
  _S2R_SaveUser_default_instance_.Shutdown();
  delete file_level_metadata[7].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::base::protobuf_base_2eproto::InitDefaults();
  _S2R_RegisterServer_default_instance_.DefaultConstruct();
  _R2S_RegisterServer_default_instance_.DefaultConstruct();
  _S2R_Login_default_instance_.DefaultConstruct();
  _R2S_Login_default_instance_.DefaultConstruct();
  _S2R_Ping_default_instance_.DefaultConstruct();
  _S2R_Create_default_instance_.DefaultConstruct();
  _R2S_Create_default_instance_.DefaultConstruct();
  _S2R_SaveUser_default_instance_.DefaultConstruct();
  _R2S_Login_default_instance_.get_mutable()->user_ = const_cast< ::base::User*>(
      ::base::User::internal_default_instance());
  _S2R_Create_default_instance_.get_mutable()->user_ = const_cast< ::base::User*>(
      ::base::User::internal_default_instance());
  _S2R_SaveUser_default_instance_.get_mutable()->user_ = const_cast< ::base::User*>(
      ::base::User::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\010sr.proto\022\002sr\032\nbase.proto\"!\n\022S2R_Regist"
      "erServer\022\013\n\003sid\030\001 \001(\r\".\n\022R2S_RegisterSer"
      "ver\022\013\n\003ret\030\001 \001(\r\022\013\n\003sid\030\002 \001(\r\")\n\tS2R_Log"
      "in\022\017\n\007tokenId\030\001 \001(\004\022\013\n\003uid\030\002 \001(\004\"C\n\tR2S_"
      "Login\022\013\n\003ret\030\001 \001(\r\022\017\n\007tokenId\030\002 \001(\004\022\030\n\004u"
      "ser\030\003 \001(\0132\n.base.User\"\034\n\010S2R_Ping\022\020\n\010now"
      "_time\030\001 \001(\r\"7\n\nS2R_Create\022\017\n\007tokenId\030\001 \001"
      "(\004\022\030\n\004user\030\002 \001(\0132\n.base.User\"*\n\nR2S_Crea"
      "te\022\013\n\003ret\030\001 \001(\r\022\017\n\007tokenId\030\002 \001(\004\"(\n\014S2R_"
      "SaveUser\022\030\n\004user\030\001 \001(\0132\n.base.User*\314\001\n\007P"
      "rotoID\022\013\n\007ID_NULL\020\000\022\033\n\025ID_S2R_RegisterSe"
      "rver\020\261\352\001\022\033\n\025ID_R2S_RegisterServer\020\262\352\001\022\022\n"
      "\014ID_S2R_Login\020\263\352\001\022\022\n\014ID_R2S_Login\020\264\352\001\022\021\n"
      "\013ID_S2R_Ping\020\265\352\001\022\023\n\rID_S2R_Create\020\267\352\001\022\023\n"
      "\rID_R2S_Create\020\270\352\001\022\025\n\017ID_S2R_SaveUser\020\271\352"
      "\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 609);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "sr.proto", &protobuf_RegisterTypes);
  ::base::protobuf_base_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_sr_2eproto

const ::google::protobuf::EnumDescriptor* ProtoID_descriptor() {
  protobuf_sr_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_sr_2eproto::file_level_enum_descriptors[0];
}
bool ProtoID_IsValid(int value) {
  switch (value) {
    case 0:
    case 30001:
    case 30002:
    case 30003:
    case 30004:
    case 30005:
    case 30007:
    case 30008:
    case 30009:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int S2R_RegisterServer::kSidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

S2R_RegisterServer::S2R_RegisterServer()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_sr_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:sr.S2R_RegisterServer)
}
S2R_RegisterServer::S2R_RegisterServer(const S2R_RegisterServer& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  sid_ = from.sid_;
  // @@protoc_insertion_point(copy_constructor:sr.S2R_RegisterServer)
}

void S2R_RegisterServer::SharedCtor() {
  sid_ = 0u;
  _cached_size_ = 0;
}

S2R_RegisterServer::~S2R_RegisterServer() {
  // @@protoc_insertion_point(destructor:sr.S2R_RegisterServer)
  SharedDtor();
}

void S2R_RegisterServer::SharedDtor() {
}

void S2R_RegisterServer::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S2R_RegisterServer::descriptor() {
  protobuf_sr_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_sr_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const S2R_RegisterServer& S2R_RegisterServer::default_instance() {
  protobuf_sr_2eproto::InitDefaults();
  return *internal_default_instance();
}

S2R_RegisterServer* S2R_RegisterServer::New(::google::protobuf::Arena* arena) const {
  S2R_RegisterServer* n = new S2R_RegisterServer;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void S2R_RegisterServer::Clear() {
// @@protoc_insertion_point(message_clear_start:sr.S2R_RegisterServer)
  sid_ = 0u;
}

bool S2R_RegisterServer::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sr.S2R_RegisterServer)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 sid = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &sid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sr.S2R_RegisterServer)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sr.S2R_RegisterServer)
  return false;
#undef DO_
}

void S2R_RegisterServer::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sr.S2R_RegisterServer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 sid = 1;
  if (this->sid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->sid(), output);
  }

  // @@protoc_insertion_point(serialize_end:sr.S2R_RegisterServer)
}

::google::protobuf::uint8* S2R_RegisterServer::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sr.S2R_RegisterServer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 sid = 1;
  if (this->sid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->sid(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:sr.S2R_RegisterServer)
  return target;
}

size_t S2R_RegisterServer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sr.S2R_RegisterServer)
  size_t total_size = 0;

  // uint32 sid = 1;
  if (this->sid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->sid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S2R_RegisterServer::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sr.S2R_RegisterServer)
  GOOGLE_DCHECK_NE(&from, this);
  const S2R_RegisterServer* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const S2R_RegisterServer>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sr.S2R_RegisterServer)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sr.S2R_RegisterServer)
    MergeFrom(*source);
  }
}

void S2R_RegisterServer::MergeFrom(const S2R_RegisterServer& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sr.S2R_RegisterServer)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.sid() != 0) {
    set_sid(from.sid());
  }
}

void S2R_RegisterServer::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sr.S2R_RegisterServer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S2R_RegisterServer::CopyFrom(const S2R_RegisterServer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sr.S2R_RegisterServer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2R_RegisterServer::IsInitialized() const {
  return true;
}

void S2R_RegisterServer::Swap(S2R_RegisterServer* other) {
  if (other == this) return;
  InternalSwap(other);
}
void S2R_RegisterServer::InternalSwap(S2R_RegisterServer* other) {
  std::swap(sid_, other->sid_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata S2R_RegisterServer::GetMetadata() const {
  protobuf_sr_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_sr_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// S2R_RegisterServer

// uint32 sid = 1;
void S2R_RegisterServer::clear_sid() {
  sid_ = 0u;
}
::google::protobuf::uint32 S2R_RegisterServer::sid() const {
  // @@protoc_insertion_point(field_get:sr.S2R_RegisterServer.sid)
  return sid_;
}
void S2R_RegisterServer::set_sid(::google::protobuf::uint32 value) {
  
  sid_ = value;
  // @@protoc_insertion_point(field_set:sr.S2R_RegisterServer.sid)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int R2S_RegisterServer::kRetFieldNumber;
const int R2S_RegisterServer::kSidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

R2S_RegisterServer::R2S_RegisterServer()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_sr_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:sr.R2S_RegisterServer)
}
R2S_RegisterServer::R2S_RegisterServer(const R2S_RegisterServer& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&ret_, &from.ret_,
    reinterpret_cast<char*>(&sid_) -
    reinterpret_cast<char*>(&ret_) + sizeof(sid_));
  // @@protoc_insertion_point(copy_constructor:sr.R2S_RegisterServer)
}

void R2S_RegisterServer::SharedCtor() {
  ::memset(&ret_, 0, reinterpret_cast<char*>(&sid_) -
    reinterpret_cast<char*>(&ret_) + sizeof(sid_));
  _cached_size_ = 0;
}

R2S_RegisterServer::~R2S_RegisterServer() {
  // @@protoc_insertion_point(destructor:sr.R2S_RegisterServer)
  SharedDtor();
}

void R2S_RegisterServer::SharedDtor() {
}

void R2S_RegisterServer::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* R2S_RegisterServer::descriptor() {
  protobuf_sr_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_sr_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const R2S_RegisterServer& R2S_RegisterServer::default_instance() {
  protobuf_sr_2eproto::InitDefaults();
  return *internal_default_instance();
}

R2S_RegisterServer* R2S_RegisterServer::New(::google::protobuf::Arena* arena) const {
  R2S_RegisterServer* n = new R2S_RegisterServer;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void R2S_RegisterServer::Clear() {
// @@protoc_insertion_point(message_clear_start:sr.R2S_RegisterServer)
  ::memset(&ret_, 0, reinterpret_cast<char*>(&sid_) -
    reinterpret_cast<char*>(&ret_) + sizeof(sid_));
}

bool R2S_RegisterServer::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sr.R2S_RegisterServer)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 ret = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &ret_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 sid = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &sid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sr.R2S_RegisterServer)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sr.R2S_RegisterServer)
  return false;
#undef DO_
}

void R2S_RegisterServer::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sr.R2S_RegisterServer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ret = 1;
  if (this->ret() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->ret(), output);
  }

  // uint32 sid = 2;
  if (this->sid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->sid(), output);
  }

  // @@protoc_insertion_point(serialize_end:sr.R2S_RegisterServer)
}

::google::protobuf::uint8* R2S_RegisterServer::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sr.R2S_RegisterServer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ret = 1;
  if (this->ret() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->ret(), target);
  }

  // uint32 sid = 2;
  if (this->sid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->sid(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:sr.R2S_RegisterServer)
  return target;
}

size_t R2S_RegisterServer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sr.R2S_RegisterServer)
  size_t total_size = 0;

  // uint32 ret = 1;
  if (this->ret() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->ret());
  }

  // uint32 sid = 2;
  if (this->sid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->sid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void R2S_RegisterServer::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sr.R2S_RegisterServer)
  GOOGLE_DCHECK_NE(&from, this);
  const R2S_RegisterServer* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const R2S_RegisterServer>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sr.R2S_RegisterServer)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sr.R2S_RegisterServer)
    MergeFrom(*source);
  }
}

void R2S_RegisterServer::MergeFrom(const R2S_RegisterServer& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sr.R2S_RegisterServer)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.ret() != 0) {
    set_ret(from.ret());
  }
  if (from.sid() != 0) {
    set_sid(from.sid());
  }
}

void R2S_RegisterServer::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sr.R2S_RegisterServer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void R2S_RegisterServer::CopyFrom(const R2S_RegisterServer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sr.R2S_RegisterServer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool R2S_RegisterServer::IsInitialized() const {
  return true;
}

void R2S_RegisterServer::Swap(R2S_RegisterServer* other) {
  if (other == this) return;
  InternalSwap(other);
}
void R2S_RegisterServer::InternalSwap(R2S_RegisterServer* other) {
  std::swap(ret_, other->ret_);
  std::swap(sid_, other->sid_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata R2S_RegisterServer::GetMetadata() const {
  protobuf_sr_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_sr_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// R2S_RegisterServer

// uint32 ret = 1;
void R2S_RegisterServer::clear_ret() {
  ret_ = 0u;
}
::google::protobuf::uint32 R2S_RegisterServer::ret() const {
  // @@protoc_insertion_point(field_get:sr.R2S_RegisterServer.ret)
  return ret_;
}
void R2S_RegisterServer::set_ret(::google::protobuf::uint32 value) {
  
  ret_ = value;
  // @@protoc_insertion_point(field_set:sr.R2S_RegisterServer.ret)
}

// uint32 sid = 2;
void R2S_RegisterServer::clear_sid() {
  sid_ = 0u;
}
::google::protobuf::uint32 R2S_RegisterServer::sid() const {
  // @@protoc_insertion_point(field_get:sr.R2S_RegisterServer.sid)
  return sid_;
}
void R2S_RegisterServer::set_sid(::google::protobuf::uint32 value) {
  
  sid_ = value;
  // @@protoc_insertion_point(field_set:sr.R2S_RegisterServer.sid)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int S2R_Login::kTokenIdFieldNumber;
const int S2R_Login::kUidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

S2R_Login::S2R_Login()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_sr_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:sr.S2R_Login)
}
S2R_Login::S2R_Login(const S2R_Login& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&tokenid_, &from.tokenid_,
    reinterpret_cast<char*>(&uid_) -
    reinterpret_cast<char*>(&tokenid_) + sizeof(uid_));
  // @@protoc_insertion_point(copy_constructor:sr.S2R_Login)
}

void S2R_Login::SharedCtor() {
  ::memset(&tokenid_, 0, reinterpret_cast<char*>(&uid_) -
    reinterpret_cast<char*>(&tokenid_) + sizeof(uid_));
  _cached_size_ = 0;
}

S2R_Login::~S2R_Login() {
  // @@protoc_insertion_point(destructor:sr.S2R_Login)
  SharedDtor();
}

void S2R_Login::SharedDtor() {
}

void S2R_Login::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S2R_Login::descriptor() {
  protobuf_sr_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_sr_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const S2R_Login& S2R_Login::default_instance() {
  protobuf_sr_2eproto::InitDefaults();
  return *internal_default_instance();
}

S2R_Login* S2R_Login::New(::google::protobuf::Arena* arena) const {
  S2R_Login* n = new S2R_Login;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void S2R_Login::Clear() {
// @@protoc_insertion_point(message_clear_start:sr.S2R_Login)
  ::memset(&tokenid_, 0, reinterpret_cast<char*>(&uid_) -
    reinterpret_cast<char*>(&tokenid_) + sizeof(uid_));
}

bool S2R_Login::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sr.S2R_Login)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 tokenId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &tokenid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 uid = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &uid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sr.S2R_Login)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sr.S2R_Login)
  return false;
#undef DO_
}

void S2R_Login::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sr.S2R_Login)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 tokenId = 1;
  if (this->tokenid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->tokenid(), output);
  }

  // uint64 uid = 2;
  if (this->uid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->uid(), output);
  }

  // @@protoc_insertion_point(serialize_end:sr.S2R_Login)
}

::google::protobuf::uint8* S2R_Login::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sr.S2R_Login)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 tokenId = 1;
  if (this->tokenid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->tokenid(), target);
  }

  // uint64 uid = 2;
  if (this->uid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->uid(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:sr.S2R_Login)
  return target;
}

size_t S2R_Login::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sr.S2R_Login)
  size_t total_size = 0;

  // uint64 tokenId = 1;
  if (this->tokenid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->tokenid());
  }

  // uint64 uid = 2;
  if (this->uid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->uid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S2R_Login::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sr.S2R_Login)
  GOOGLE_DCHECK_NE(&from, this);
  const S2R_Login* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const S2R_Login>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sr.S2R_Login)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sr.S2R_Login)
    MergeFrom(*source);
  }
}

void S2R_Login::MergeFrom(const S2R_Login& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sr.S2R_Login)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.tokenid() != 0) {
    set_tokenid(from.tokenid());
  }
  if (from.uid() != 0) {
    set_uid(from.uid());
  }
}

void S2R_Login::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sr.S2R_Login)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S2R_Login::CopyFrom(const S2R_Login& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sr.S2R_Login)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2R_Login::IsInitialized() const {
  return true;
}

void S2R_Login::Swap(S2R_Login* other) {
  if (other == this) return;
  InternalSwap(other);
}
void S2R_Login::InternalSwap(S2R_Login* other) {
  std::swap(tokenid_, other->tokenid_);
  std::swap(uid_, other->uid_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata S2R_Login::GetMetadata() const {
  protobuf_sr_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_sr_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// S2R_Login

// uint64 tokenId = 1;
void S2R_Login::clear_tokenid() {
  tokenid_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 S2R_Login::tokenid() const {
  // @@protoc_insertion_point(field_get:sr.S2R_Login.tokenId)
  return tokenid_;
}
void S2R_Login::set_tokenid(::google::protobuf::uint64 value) {
  
  tokenid_ = value;
  // @@protoc_insertion_point(field_set:sr.S2R_Login.tokenId)
}

// uint64 uid = 2;
void S2R_Login::clear_uid() {
  uid_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 S2R_Login::uid() const {
  // @@protoc_insertion_point(field_get:sr.S2R_Login.uid)
  return uid_;
}
void S2R_Login::set_uid(::google::protobuf::uint64 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:sr.S2R_Login.uid)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int R2S_Login::kRetFieldNumber;
const int R2S_Login::kTokenIdFieldNumber;
const int R2S_Login::kUserFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

R2S_Login::R2S_Login()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_sr_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:sr.R2S_Login)
}
R2S_Login::R2S_Login(const R2S_Login& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_user()) {
    user_ = new ::base::User(*from.user_);
  } else {
    user_ = NULL;
  }
  ::memcpy(&tokenid_, &from.tokenid_,
    reinterpret_cast<char*>(&ret_) -
    reinterpret_cast<char*>(&tokenid_) + sizeof(ret_));
  // @@protoc_insertion_point(copy_constructor:sr.R2S_Login)
}

void R2S_Login::SharedCtor() {
  ::memset(&user_, 0, reinterpret_cast<char*>(&ret_) -
    reinterpret_cast<char*>(&user_) + sizeof(ret_));
  _cached_size_ = 0;
}

R2S_Login::~R2S_Login() {
  // @@protoc_insertion_point(destructor:sr.R2S_Login)
  SharedDtor();
}

void R2S_Login::SharedDtor() {
  if (this != internal_default_instance()) {
    delete user_;
  }
}

void R2S_Login::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* R2S_Login::descriptor() {
  protobuf_sr_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_sr_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const R2S_Login& R2S_Login::default_instance() {
  protobuf_sr_2eproto::InitDefaults();
  return *internal_default_instance();
}

R2S_Login* R2S_Login::New(::google::protobuf::Arena* arena) const {
  R2S_Login* n = new R2S_Login;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void R2S_Login::Clear() {
// @@protoc_insertion_point(message_clear_start:sr.R2S_Login)
  if (GetArenaNoVirtual() == NULL && user_ != NULL) {
    delete user_;
  }
  user_ = NULL;
  ::memset(&tokenid_, 0, reinterpret_cast<char*>(&ret_) -
    reinterpret_cast<char*>(&tokenid_) + sizeof(ret_));
}

bool R2S_Login::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sr.R2S_Login)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 ret = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &ret_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 tokenId = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &tokenid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .base.User user = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_user()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sr.R2S_Login)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sr.R2S_Login)
  return false;
#undef DO_
}

void R2S_Login::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sr.R2S_Login)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ret = 1;
  if (this->ret() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->ret(), output);
  }

  // uint64 tokenId = 2;
  if (this->tokenid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->tokenid(), output);
  }

  // .base.User user = 3;
  if (this->has_user()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->user_, output);
  }

  // @@protoc_insertion_point(serialize_end:sr.R2S_Login)
}

::google::protobuf::uint8* R2S_Login::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sr.R2S_Login)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ret = 1;
  if (this->ret() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->ret(), target);
  }

  // uint64 tokenId = 2;
  if (this->tokenid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->tokenid(), target);
  }

  // .base.User user = 3;
  if (this->has_user()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *this->user_, deterministic, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:sr.R2S_Login)
  return target;
}

size_t R2S_Login::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sr.R2S_Login)
  size_t total_size = 0;

  // .base.User user = 3;
  if (this->has_user()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->user_);
  }

  // uint64 tokenId = 2;
  if (this->tokenid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->tokenid());
  }

  // uint32 ret = 1;
  if (this->ret() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->ret());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void R2S_Login::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sr.R2S_Login)
  GOOGLE_DCHECK_NE(&from, this);
  const R2S_Login* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const R2S_Login>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sr.R2S_Login)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sr.R2S_Login)
    MergeFrom(*source);
  }
}

void R2S_Login::MergeFrom(const R2S_Login& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sr.R2S_Login)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_user()) {
    mutable_user()->::base::User::MergeFrom(from.user());
  }
  if (from.tokenid() != 0) {
    set_tokenid(from.tokenid());
  }
  if (from.ret() != 0) {
    set_ret(from.ret());
  }
}

void R2S_Login::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sr.R2S_Login)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void R2S_Login::CopyFrom(const R2S_Login& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sr.R2S_Login)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool R2S_Login::IsInitialized() const {
  return true;
}

void R2S_Login::Swap(R2S_Login* other) {
  if (other == this) return;
  InternalSwap(other);
}
void R2S_Login::InternalSwap(R2S_Login* other) {
  std::swap(user_, other->user_);
  std::swap(tokenid_, other->tokenid_);
  std::swap(ret_, other->ret_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata R2S_Login::GetMetadata() const {
  protobuf_sr_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_sr_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// R2S_Login

// uint32 ret = 1;
void R2S_Login::clear_ret() {
  ret_ = 0u;
}
::google::protobuf::uint32 R2S_Login::ret() const {
  // @@protoc_insertion_point(field_get:sr.R2S_Login.ret)
  return ret_;
}
void R2S_Login::set_ret(::google::protobuf::uint32 value) {
  
  ret_ = value;
  // @@protoc_insertion_point(field_set:sr.R2S_Login.ret)
}

// uint64 tokenId = 2;
void R2S_Login::clear_tokenid() {
  tokenid_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 R2S_Login::tokenid() const {
  // @@protoc_insertion_point(field_get:sr.R2S_Login.tokenId)
  return tokenid_;
}
void R2S_Login::set_tokenid(::google::protobuf::uint64 value) {
  
  tokenid_ = value;
  // @@protoc_insertion_point(field_set:sr.R2S_Login.tokenId)
}

// .base.User user = 3;
bool R2S_Login::has_user() const {
  return this != internal_default_instance() && user_ != NULL;
}
void R2S_Login::clear_user() {
  if (GetArenaNoVirtual() == NULL && user_ != NULL) delete user_;
  user_ = NULL;
}
const ::base::User& R2S_Login::user() const {
  // @@protoc_insertion_point(field_get:sr.R2S_Login.user)
  return user_ != NULL ? *user_
                         : *::base::User::internal_default_instance();
}
::base::User* R2S_Login::mutable_user() {
  
  if (user_ == NULL) {
    user_ = new ::base::User;
  }
  // @@protoc_insertion_point(field_mutable:sr.R2S_Login.user)
  return user_;
}
::base::User* R2S_Login::release_user() {
  // @@protoc_insertion_point(field_release:sr.R2S_Login.user)
  
  ::base::User* temp = user_;
  user_ = NULL;
  return temp;
}
void R2S_Login::set_allocated_user(::base::User* user) {
  delete user_;
  user_ = user;
  if (user) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:sr.R2S_Login.user)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int S2R_Ping::kNowTimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

S2R_Ping::S2R_Ping()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_sr_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:sr.S2R_Ping)
}
S2R_Ping::S2R_Ping(const S2R_Ping& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  now_time_ = from.now_time_;
  // @@protoc_insertion_point(copy_constructor:sr.S2R_Ping)
}

void S2R_Ping::SharedCtor() {
  now_time_ = 0u;
  _cached_size_ = 0;
}

S2R_Ping::~S2R_Ping() {
  // @@protoc_insertion_point(destructor:sr.S2R_Ping)
  SharedDtor();
}

void S2R_Ping::SharedDtor() {
}

void S2R_Ping::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S2R_Ping::descriptor() {
  protobuf_sr_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_sr_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const S2R_Ping& S2R_Ping::default_instance() {
  protobuf_sr_2eproto::InitDefaults();
  return *internal_default_instance();
}

S2R_Ping* S2R_Ping::New(::google::protobuf::Arena* arena) const {
  S2R_Ping* n = new S2R_Ping;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void S2R_Ping::Clear() {
// @@protoc_insertion_point(message_clear_start:sr.S2R_Ping)
  now_time_ = 0u;
}

bool S2R_Ping::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sr.S2R_Ping)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 now_time = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &now_time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sr.S2R_Ping)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sr.S2R_Ping)
  return false;
#undef DO_
}

void S2R_Ping::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sr.S2R_Ping)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 now_time = 1;
  if (this->now_time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->now_time(), output);
  }

  // @@protoc_insertion_point(serialize_end:sr.S2R_Ping)
}

::google::protobuf::uint8* S2R_Ping::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sr.S2R_Ping)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 now_time = 1;
  if (this->now_time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->now_time(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:sr.S2R_Ping)
  return target;
}

size_t S2R_Ping::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sr.S2R_Ping)
  size_t total_size = 0;

  // uint32 now_time = 1;
  if (this->now_time() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->now_time());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S2R_Ping::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sr.S2R_Ping)
  GOOGLE_DCHECK_NE(&from, this);
  const S2R_Ping* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const S2R_Ping>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sr.S2R_Ping)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sr.S2R_Ping)
    MergeFrom(*source);
  }
}

void S2R_Ping::MergeFrom(const S2R_Ping& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sr.S2R_Ping)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.now_time() != 0) {
    set_now_time(from.now_time());
  }
}

void S2R_Ping::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sr.S2R_Ping)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S2R_Ping::CopyFrom(const S2R_Ping& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sr.S2R_Ping)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2R_Ping::IsInitialized() const {
  return true;
}

void S2R_Ping::Swap(S2R_Ping* other) {
  if (other == this) return;
  InternalSwap(other);
}
void S2R_Ping::InternalSwap(S2R_Ping* other) {
  std::swap(now_time_, other->now_time_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata S2R_Ping::GetMetadata() const {
  protobuf_sr_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_sr_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// S2R_Ping

// uint32 now_time = 1;
void S2R_Ping::clear_now_time() {
  now_time_ = 0u;
}
::google::protobuf::uint32 S2R_Ping::now_time() const {
  // @@protoc_insertion_point(field_get:sr.S2R_Ping.now_time)
  return now_time_;
}
void S2R_Ping::set_now_time(::google::protobuf::uint32 value) {
  
  now_time_ = value;
  // @@protoc_insertion_point(field_set:sr.S2R_Ping.now_time)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int S2R_Create::kTokenIdFieldNumber;
const int S2R_Create::kUserFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

S2R_Create::S2R_Create()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_sr_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:sr.S2R_Create)
}
S2R_Create::S2R_Create(const S2R_Create& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_user()) {
    user_ = new ::base::User(*from.user_);
  } else {
    user_ = NULL;
  }
  tokenid_ = from.tokenid_;
  // @@protoc_insertion_point(copy_constructor:sr.S2R_Create)
}

void S2R_Create::SharedCtor() {
  ::memset(&user_, 0, reinterpret_cast<char*>(&tokenid_) -
    reinterpret_cast<char*>(&user_) + sizeof(tokenid_));
  _cached_size_ = 0;
}

S2R_Create::~S2R_Create() {
  // @@protoc_insertion_point(destructor:sr.S2R_Create)
  SharedDtor();
}

void S2R_Create::SharedDtor() {
  if (this != internal_default_instance()) {
    delete user_;
  }
}

void S2R_Create::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S2R_Create::descriptor() {
  protobuf_sr_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_sr_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const S2R_Create& S2R_Create::default_instance() {
  protobuf_sr_2eproto::InitDefaults();
  return *internal_default_instance();
}

S2R_Create* S2R_Create::New(::google::protobuf::Arena* arena) const {
  S2R_Create* n = new S2R_Create;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void S2R_Create::Clear() {
// @@protoc_insertion_point(message_clear_start:sr.S2R_Create)
  if (GetArenaNoVirtual() == NULL && user_ != NULL) {
    delete user_;
  }
  user_ = NULL;
  tokenid_ = GOOGLE_ULONGLONG(0);
}

bool S2R_Create::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sr.S2R_Create)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 tokenId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &tokenid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .base.User user = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_user()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sr.S2R_Create)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sr.S2R_Create)
  return false;
#undef DO_
}

void S2R_Create::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sr.S2R_Create)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 tokenId = 1;
  if (this->tokenid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->tokenid(), output);
  }

  // .base.User user = 2;
  if (this->has_user()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->user_, output);
  }

  // @@protoc_insertion_point(serialize_end:sr.S2R_Create)
}

::google::protobuf::uint8* S2R_Create::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sr.S2R_Create)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 tokenId = 1;
  if (this->tokenid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->tokenid(), target);
  }

  // .base.User user = 2;
  if (this->has_user()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->user_, deterministic, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:sr.S2R_Create)
  return target;
}

size_t S2R_Create::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sr.S2R_Create)
  size_t total_size = 0;

  // .base.User user = 2;
  if (this->has_user()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->user_);
  }

  // uint64 tokenId = 1;
  if (this->tokenid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->tokenid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S2R_Create::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sr.S2R_Create)
  GOOGLE_DCHECK_NE(&from, this);
  const S2R_Create* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const S2R_Create>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sr.S2R_Create)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sr.S2R_Create)
    MergeFrom(*source);
  }
}

void S2R_Create::MergeFrom(const S2R_Create& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sr.S2R_Create)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_user()) {
    mutable_user()->::base::User::MergeFrom(from.user());
  }
  if (from.tokenid() != 0) {
    set_tokenid(from.tokenid());
  }
}

void S2R_Create::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sr.S2R_Create)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S2R_Create::CopyFrom(const S2R_Create& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sr.S2R_Create)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2R_Create::IsInitialized() const {
  return true;
}

void S2R_Create::Swap(S2R_Create* other) {
  if (other == this) return;
  InternalSwap(other);
}
void S2R_Create::InternalSwap(S2R_Create* other) {
  std::swap(user_, other->user_);
  std::swap(tokenid_, other->tokenid_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata S2R_Create::GetMetadata() const {
  protobuf_sr_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_sr_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// S2R_Create

// uint64 tokenId = 1;
void S2R_Create::clear_tokenid() {
  tokenid_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 S2R_Create::tokenid() const {
  // @@protoc_insertion_point(field_get:sr.S2R_Create.tokenId)
  return tokenid_;
}
void S2R_Create::set_tokenid(::google::protobuf::uint64 value) {
  
  tokenid_ = value;
  // @@protoc_insertion_point(field_set:sr.S2R_Create.tokenId)
}

// .base.User user = 2;
bool S2R_Create::has_user() const {
  return this != internal_default_instance() && user_ != NULL;
}
void S2R_Create::clear_user() {
  if (GetArenaNoVirtual() == NULL && user_ != NULL) delete user_;
  user_ = NULL;
}
const ::base::User& S2R_Create::user() const {
  // @@protoc_insertion_point(field_get:sr.S2R_Create.user)
  return user_ != NULL ? *user_
                         : *::base::User::internal_default_instance();
}
::base::User* S2R_Create::mutable_user() {
  
  if (user_ == NULL) {
    user_ = new ::base::User;
  }
  // @@protoc_insertion_point(field_mutable:sr.S2R_Create.user)
  return user_;
}
::base::User* S2R_Create::release_user() {
  // @@protoc_insertion_point(field_release:sr.S2R_Create.user)
  
  ::base::User* temp = user_;
  user_ = NULL;
  return temp;
}
void S2R_Create::set_allocated_user(::base::User* user) {
  delete user_;
  user_ = user;
  if (user) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:sr.S2R_Create.user)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int R2S_Create::kRetFieldNumber;
const int R2S_Create::kTokenIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

R2S_Create::R2S_Create()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_sr_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:sr.R2S_Create)
}
R2S_Create::R2S_Create(const R2S_Create& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&tokenid_, &from.tokenid_,
    reinterpret_cast<char*>(&ret_) -
    reinterpret_cast<char*>(&tokenid_) + sizeof(ret_));
  // @@protoc_insertion_point(copy_constructor:sr.R2S_Create)
}

void R2S_Create::SharedCtor() {
  ::memset(&tokenid_, 0, reinterpret_cast<char*>(&ret_) -
    reinterpret_cast<char*>(&tokenid_) + sizeof(ret_));
  _cached_size_ = 0;
}

R2S_Create::~R2S_Create() {
  // @@protoc_insertion_point(destructor:sr.R2S_Create)
  SharedDtor();
}

void R2S_Create::SharedDtor() {
}

void R2S_Create::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* R2S_Create::descriptor() {
  protobuf_sr_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_sr_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const R2S_Create& R2S_Create::default_instance() {
  protobuf_sr_2eproto::InitDefaults();
  return *internal_default_instance();
}

R2S_Create* R2S_Create::New(::google::protobuf::Arena* arena) const {
  R2S_Create* n = new R2S_Create;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void R2S_Create::Clear() {
// @@protoc_insertion_point(message_clear_start:sr.R2S_Create)
  ::memset(&tokenid_, 0, reinterpret_cast<char*>(&ret_) -
    reinterpret_cast<char*>(&tokenid_) + sizeof(ret_));
}

bool R2S_Create::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sr.R2S_Create)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 ret = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &ret_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 tokenId = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &tokenid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sr.R2S_Create)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sr.R2S_Create)
  return false;
#undef DO_
}

void R2S_Create::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sr.R2S_Create)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ret = 1;
  if (this->ret() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->ret(), output);
  }

  // uint64 tokenId = 2;
  if (this->tokenid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->tokenid(), output);
  }

  // @@protoc_insertion_point(serialize_end:sr.R2S_Create)
}

::google::protobuf::uint8* R2S_Create::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sr.R2S_Create)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ret = 1;
  if (this->ret() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->ret(), target);
  }

  // uint64 tokenId = 2;
  if (this->tokenid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->tokenid(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:sr.R2S_Create)
  return target;
}

size_t R2S_Create::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sr.R2S_Create)
  size_t total_size = 0;

  // uint64 tokenId = 2;
  if (this->tokenid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->tokenid());
  }

  // uint32 ret = 1;
  if (this->ret() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->ret());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void R2S_Create::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sr.R2S_Create)
  GOOGLE_DCHECK_NE(&from, this);
  const R2S_Create* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const R2S_Create>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sr.R2S_Create)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sr.R2S_Create)
    MergeFrom(*source);
  }
}

void R2S_Create::MergeFrom(const R2S_Create& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sr.R2S_Create)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.tokenid() != 0) {
    set_tokenid(from.tokenid());
  }
  if (from.ret() != 0) {
    set_ret(from.ret());
  }
}

void R2S_Create::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sr.R2S_Create)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void R2S_Create::CopyFrom(const R2S_Create& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sr.R2S_Create)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool R2S_Create::IsInitialized() const {
  return true;
}

void R2S_Create::Swap(R2S_Create* other) {
  if (other == this) return;
  InternalSwap(other);
}
void R2S_Create::InternalSwap(R2S_Create* other) {
  std::swap(tokenid_, other->tokenid_);
  std::swap(ret_, other->ret_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata R2S_Create::GetMetadata() const {
  protobuf_sr_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_sr_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// R2S_Create

// uint32 ret = 1;
void R2S_Create::clear_ret() {
  ret_ = 0u;
}
::google::protobuf::uint32 R2S_Create::ret() const {
  // @@protoc_insertion_point(field_get:sr.R2S_Create.ret)
  return ret_;
}
void R2S_Create::set_ret(::google::protobuf::uint32 value) {
  
  ret_ = value;
  // @@protoc_insertion_point(field_set:sr.R2S_Create.ret)
}

// uint64 tokenId = 2;
void R2S_Create::clear_tokenid() {
  tokenid_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 R2S_Create::tokenid() const {
  // @@protoc_insertion_point(field_get:sr.R2S_Create.tokenId)
  return tokenid_;
}
void R2S_Create::set_tokenid(::google::protobuf::uint64 value) {
  
  tokenid_ = value;
  // @@protoc_insertion_point(field_set:sr.R2S_Create.tokenId)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int S2R_SaveUser::kUserFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

S2R_SaveUser::S2R_SaveUser()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_sr_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:sr.S2R_SaveUser)
}
S2R_SaveUser::S2R_SaveUser(const S2R_SaveUser& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_user()) {
    user_ = new ::base::User(*from.user_);
  } else {
    user_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:sr.S2R_SaveUser)
}

void S2R_SaveUser::SharedCtor() {
  user_ = NULL;
  _cached_size_ = 0;
}

S2R_SaveUser::~S2R_SaveUser() {
  // @@protoc_insertion_point(destructor:sr.S2R_SaveUser)
  SharedDtor();
}

void S2R_SaveUser::SharedDtor() {
  if (this != internal_default_instance()) {
    delete user_;
  }
}

void S2R_SaveUser::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S2R_SaveUser::descriptor() {
  protobuf_sr_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_sr_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const S2R_SaveUser& S2R_SaveUser::default_instance() {
  protobuf_sr_2eproto::InitDefaults();
  return *internal_default_instance();
}

S2R_SaveUser* S2R_SaveUser::New(::google::protobuf::Arena* arena) const {
  S2R_SaveUser* n = new S2R_SaveUser;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void S2R_SaveUser::Clear() {
// @@protoc_insertion_point(message_clear_start:sr.S2R_SaveUser)
  if (GetArenaNoVirtual() == NULL && user_ != NULL) {
    delete user_;
  }
  user_ = NULL;
}

bool S2R_SaveUser::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sr.S2R_SaveUser)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .base.User user = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_user()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sr.S2R_SaveUser)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sr.S2R_SaveUser)
  return false;
#undef DO_
}

void S2R_SaveUser::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sr.S2R_SaveUser)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .base.User user = 1;
  if (this->has_user()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->user_, output);
  }

  // @@protoc_insertion_point(serialize_end:sr.S2R_SaveUser)
}

::google::protobuf::uint8* S2R_SaveUser::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sr.S2R_SaveUser)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .base.User user = 1;
  if (this->has_user()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->user_, deterministic, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:sr.S2R_SaveUser)
  return target;
}

size_t S2R_SaveUser::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sr.S2R_SaveUser)
  size_t total_size = 0;

  // .base.User user = 1;
  if (this->has_user()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->user_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S2R_SaveUser::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sr.S2R_SaveUser)
  GOOGLE_DCHECK_NE(&from, this);
  const S2R_SaveUser* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const S2R_SaveUser>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sr.S2R_SaveUser)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sr.S2R_SaveUser)
    MergeFrom(*source);
  }
}

void S2R_SaveUser::MergeFrom(const S2R_SaveUser& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sr.S2R_SaveUser)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_user()) {
    mutable_user()->::base::User::MergeFrom(from.user());
  }
}

void S2R_SaveUser::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sr.S2R_SaveUser)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S2R_SaveUser::CopyFrom(const S2R_SaveUser& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sr.S2R_SaveUser)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2R_SaveUser::IsInitialized() const {
  return true;
}

void S2R_SaveUser::Swap(S2R_SaveUser* other) {
  if (other == this) return;
  InternalSwap(other);
}
void S2R_SaveUser::InternalSwap(S2R_SaveUser* other) {
  std::swap(user_, other->user_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata S2R_SaveUser::GetMetadata() const {
  protobuf_sr_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_sr_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// S2R_SaveUser

// .base.User user = 1;
bool S2R_SaveUser::has_user() const {
  return this != internal_default_instance() && user_ != NULL;
}
void S2R_SaveUser::clear_user() {
  if (GetArenaNoVirtual() == NULL && user_ != NULL) delete user_;
  user_ = NULL;
}
const ::base::User& S2R_SaveUser::user() const {
  // @@protoc_insertion_point(field_get:sr.S2R_SaveUser.user)
  return user_ != NULL ? *user_
                         : *::base::User::internal_default_instance();
}
::base::User* S2R_SaveUser::mutable_user() {
  
  if (user_ == NULL) {
    user_ = new ::base::User;
  }
  // @@protoc_insertion_point(field_mutable:sr.S2R_SaveUser.user)
  return user_;
}
::base::User* S2R_SaveUser::release_user() {
  // @@protoc_insertion_point(field_release:sr.S2R_SaveUser.user)
  
  ::base::User* temp = user_;
  user_ = NULL;
  return temp;
}
void S2R_SaveUser::set_allocated_user(::base::User* user) {
  delete user_;
  user_ = user;
  if (user) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:sr.S2R_SaveUser.user)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace sr

// @@protoc_insertion_point(global_scope)
